// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUser struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,3,opt,name=confirmPassword,proto3" json:"confirmPassword,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUser) Reset()         { *m = CreateUser{} }
func (m *CreateUser) String() string { return proto.CompactTextString(m) }
func (*CreateUser) ProtoMessage()    {}
func (*CreateUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *CreateUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUser.Unmarshal(m, b)
}
func (m *CreateUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUser.Marshal(b, m, deterministic)
}
func (m *CreateUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUser.Merge(m, src)
}
func (m *CreateUser) XXX_Size() int {
	return xxx_messageInfo_CreateUser.Size(m)
}
func (m *CreateUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUser.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUser proto.InternalMessageInfo

func (m *CreateUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUser) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

func (m *CreateUser) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUser) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Visible              bool     `protobuf:"varint,5,opt,name=visible,proto3" json:"visible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func init() {
	proto.RegisterType((*CreateUser)(nil), "types.CreateUser")
	proto.RegisterType((*User)(nil), "types.User")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x16, 0x31, 0x72, 0x71,
	0x39, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x86, 0x16, 0xa7, 0x16, 0x09, 0x89, 0x70, 0xb1, 0xa6, 0xe6,
	0x26, 0x66, 0xe6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0x52, 0x5c, 0x1c,
	0x05, 0x89, 0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12, 0x4c, 0x60, 0x09, 0x38, 0x5f, 0x48, 0x83,
	0x8b, 0x3f, 0x39, 0x3f, 0x2f, 0x2d, 0xb3, 0x28, 0x37, 0x00, 0xa6, 0x84, 0x19, 0xac, 0x04, 0x5d,
	0x58, 0x48, 0x86, 0x8b, 0x33, 0x2d, 0xb3, 0xa8, 0xb8, 0xc4, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x05,
	0xac, 0x06, 0x21, 0x00, 0xb2, 0x23, 0x27, 0x11, 0x2a, 0xc9, 0x0a, 0xb1, 0x03, 0xc6, 0x57, 0x6a,
	0x60, 0xe4, 0x62, 0x01, 0x3b, 0x8f, 0x8f, 0x8b, 0x29, 0x33, 0x05, 0xec, 0x36, 0xe6, 0x20, 0xa6,
	0xcc, 0x14, 0x84, 0x73, 0x99, 0x90, 0x9d, 0x8b, 0x62, 0x11, 0x33, 0x3e, 0x8b, 0x58, 0x50, 0x2d,
	0x12, 0x92, 0xe0, 0x62, 0x2f, 0xcb, 0x2c, 0xce, 0x4c, 0xca, 0x81, 0xb8, 0x81, 0x23, 0x08, 0xc6,
	0x75, 0x62, 0x8b, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x4e, 0x62, 0x03, 0x87, 0x9e, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xa5, 0x74, 0xdd, 0x56, 0x4c, 0x01, 0x00, 0x00,
}
